config/routes.rb
Rails.application.routes.draw do
  
    root 'welcomes#index'
	resources :formularios
	devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/formulario.rb
class Formulario < ApplicationRecord


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/formularios_controller.rb
class FormulariosController < ApplicationController
	def index
		@formularios = Formulario.all
	end

	def show
		@formulario = Formulario.find(params[:id])
	end

	def new
		@formulario = Formulario.new
	end

	def edit
		@formulario = Formulario.find(params[:id])
	end

	def create
		@formulario = Formulario.new(formulario_params)
 		@formulario.save
 		redirect_to @formulario
	end

	def update
		@formulario = Formulario.find(params[:id])
		if  @formulario.update(formulario_params)
        	format.html { redirect_to @formulario, notice: 'Se actualizaron tus datos.' }
        	
      	else
        	format.html { render :edit }
        	
      	end
	end

	def destroy
		@formulario = Formulario.find(params[:id])
		@formulario.destroy
        respond_to do |format|
        format.html { redirect_to formulario_url, notice: 'Se borro la informacion' }
        end
	end	

	private
	def formulario_params
		params.require(:formulario).permit(:nombre_mama, :nombre_hijo, :edad_hijo, :direccion, :habilidades)
	end


end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/formularios_helper.rb
module FormulariosHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/formularios/edit.html.erb
<h1>Diligencia los siguientes datos</h1>


<%= form_with scope: :formulario, url: formularios_path, local: true do |form| %>

  <p>
    <%= form.label :nombre_mama %><br>
    <%= form.text_field :nombre_mama %>
  </p>
  <p>
    <%= form.label :nombre_hijo %><br>
    <%= form.text_field :nombre_hijo %>
  </p>
  <p>
    <%= form.label :edad_hijo %><br>
    <%= form.text_field :edad %>
  </p>
  <p>
    <%= form.label :direccion %><br>
    <%= form.text_field :direccion %>
  </p>
  <p>
    <%= form.label :habilidades %><br>
    <%= form.text_field :habilidades %>
  </p>

  <%= link_to 'Back', formularios_path %>

 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/formularios/index.html.erb
<h1>Mamas en red</h1>
 
<table>
  <tr>
    <th>Mama</th>
    <th>Hijo</th>
    <th>Edad hijo</th>
    <th>Direccion</th>
    <th>Habilidades</th>
    <th></th>
  </tr>
 
  <% @formularios.each do |formulario| %>
    <tr>
      <td><%= formulario.nombre_mama %></td>
      <td><%= formulario.nombre_hijo %></td>
      <td><%= formulario.edad %></td>
      <td><%= formulario.habilidades %></td>
      <td><%= link_to 'Show', formulario_path(formulario) %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'New mom', new_formulario_path %>

app/views/formularios/new.html.erb
<h1>Diligencia los siguientes datos</h1>


<%= form_with scope: :formulario, url: formularios_path, local: true do |form| %>

  <p>
    <%= form.label :nombre_mama %><br>
    <%= form.text_field :nombre_mama %>
  </p>
  <p>
    <%= form.label :nombre_hijo %><br>
    <%= form.text_field :nombre_hijo %>
  </p>
  <p>
    <%= form.label :edad_hijo %><br>
    <%= form.text_field :edad %>
  </p>
  <p>
    <%= form.label :direccion %><br>
    <%= form.text_field :direccion %>
  </p>
  <p>
    <%= form.label :habilidades %><br>
    <%= form.text_field :habilidades %>
  </p>

  <%= link_to 'Back', formularios_path %>

 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/formularios/show.html.erb
<p>
   <strong>Mama:</strong>	
   <%= @formulario.nombre_mama %> 
</p>
 
 <p>

  <strong>Hijo/a:</strong>
  <%= @formulario.nombre_hijo %>
</p>

<p>
  <strong>Edad hijo/a:</strong>
  <%= @formulario.edad %> 
</p>

<p>
  <strong>Direccion:</strong>
  <%= @formulario.direccion %> 
</p>

<p>
  <strong>Habilidades:</strong>
  <%= @formulario.habilidades %> 
</p>

<%= link_to 'Edit', edit_formulario_path  %>
<%= link_to 'Remove', @formulario, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mom3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <div>
  <% if user_signed_in? %>
    <%= link_to "Salir", destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to "Registrarse", new_user_registration_path %>
    <%= link_to "Ingresar", new_user_session_path %>
  <% end %>
  </div>

    <%= yield %>
  </body>
</html>

app/views/welcomes/index.html.erb
<h1>Hello Moms</h1>
<%= link_to 'Mamas en linea', controller: 'formularios' %>